### ISSUE TITLE
Please, add a `delete` method

### ISSUE THREAD

**Issue by CoolMind** [googledrive/android-delete#1]
Thanks for a nice sample, but it cannot be compiled (https://github.com/googledrive/android-delete/blob/master/app/src/main/java/drive/play/android/samples/com/drivedeletesample/MainActivity.java).
In these lines:

    DriveFile sumFile = ...
    com.google.android.gms.common.api.Status deleteStatus =
        sumFile.delete(mGoogleApiClient).await();

a method `delete` doesn't exist. In a parent class DriveResource it exists as an abstract
(https://developers.google.com/android/reference/com/google/android/gms/drive/DriveResource#delete(com.google.android.gms.common.api.GoogleApiClient)).

**Comment by kroikie** [comment]
delete was added in the latest version of Google Play Services, please check SDK Manager to be sure that you are using the latest version.

**Comment by CoolMind** [comment]
@kroikie, thanks for a rapid answer. Sure, I was having the latest version of SDK at the moment of writing the issue.

![playservices](https://cloud.githubusercontent.com/assets/10630436/8404376/226d674a-1e55-11e5-9e2e-6fcb2d526075.png)

**Comment by kroikie** [comment]
The delete method should be available from Google Play Services 7.5.0. I'm not able to reproduce this issue, however try using **7.5.0** for the play-services dependencies in the build.gradle file instead of **7.5.+** and re-sync your project. Also I'd suggest cleaning and rebuilding the project.

**Comment by CoolMind** [comment]
@kroikie, thank you very much!
I am making a project using GDAA for several months and recently have included trash and delete ability. But forgot to increase a version of Google Play Services in dependencies. Not it is compiled.
